//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAIV_WEB.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_PersonGroup_Mapping
    {
        public int ID { get; set; }
        public string UserId { get; set; }
        public int PersonGroupId { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PersonGroup PersonGroup { get; set; }
    }
}
