
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AAIV_WEB.Models.Entities.Repositories
{

using System;
    using System.Collections.Generic;
    

public partial interface IConceptRepository : SkyWeb.DatVM.Data.IBaseRepository<Concept>
{
}

public partial class ConceptRepository : SkyWeb.DatVM.Data.BaseRepository<Concept>, IConceptRepository
{
	public ConceptRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    {
    }
}

}
