
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AAIV_WEB.Models.Entities.Repositories
{

using System;
    using System.Collections.Generic;
    

public partial interface ILogRepository : SkyWeb.DatVM.Data.IBaseRepository<Log>
{
}

public partial class LogRepository : SkyWeb.DatVM.Data.BaseRepository<Log>, ILogRepository
{
	public LogRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    {
    }
}

}
