//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Face
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public string ImageURL { get; set; }
        public bool Active { get; set; }
    
        public virtual tbl_Person tbl_Person { get; set; }
    }
}
