//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Person()
        {
            this.tbl_Face = new HashSet<tbl_Face>();
        }
    
        public int ID { get; set; }
        public int PersonGroupID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Gender { get; set; }
        public string ImageURL { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Face> tbl_Face { get; set; }
        public virtual tbl_PersonGroup tbl_PersonGroup { get; set; }
    }
}
