//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAIV_WEB.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_PersonGroup_MappingViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Models.Entities.User_PersonGroup_Mapping>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual string UserId { get; set; }
    			public virtual int PersonGroupId { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public User_PersonGroup_MappingViewModel() : base() { }
    	public User_PersonGroup_MappingViewModel(Models.Entities.User_PersonGroup_Mapping entity) : base(entity) { }
    
    }
}
