//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAIV_WEB.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IConceptService : SkyWeb.DatVM.Data.IBaseService<Concept>
    {
    }
    
    public partial class ConceptService : SkyWeb.DatVM.Data.BaseService<Concept>, IConceptService
    {
        public ConceptService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IConceptRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
