//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface IC__MigrationHistoryService : Data.Service.IBaseService<C__MigrationHistory>
    {
    }
    
    public partial class C__MigrationHistoryService : Data.Service.BaseService<C__MigrationHistory>, IC__MigrationHistoryService
    {
        public C__MigrationHistoryService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.IC__MigrationHistoryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
