//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface IFaceService : Data.Service.IBaseService<Face>
    {
    }
    
    public partial class FaceService : Data.Service.BaseService<Face>, IFaceService
    {
        public FaceService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.IFaceRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
