//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface ILogService : Data.Service.IBaseService<Log>
    {
    }
    
    public partial class LogService : Data.Service.BaseService<Log>, ILogService
    {
        public LogService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.ILogRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
