//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface IPersonService : Data.Service.IBaseService<Person>
    {
    }
    
    public partial class PersonService : Data.Service.BaseService<Person>, IPersonService
    {
        public PersonService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.IPersonRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
