//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface IPersonGroupService : Data.Service.IBaseService<PersonGroup>
    {
    }
    
    public partial class PersonGroupService : Data.Service.BaseService<PersonGroup>, IPersonGroupService
    {
        public PersonGroupService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.IPersonGroupRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
