//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface Itbl_FaceService : Data.Service.IBaseService<tbl_Face>
    {
    }
    
    public partial class tbl_FaceService : Data.Service.BaseService<tbl_Face>, Itbl_FaceService
    {
        public tbl_FaceService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.Itbl_FaceRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
