//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface Itbl_PersonGroupService : Data.Service.IBaseService<tbl_PersonGroup>
    {
    }
    
    public partial class tbl_PersonGroupService : Data.Service.BaseService<tbl_PersonGroup>, Itbl_PersonGroupService
    {
        public tbl_PersonGroupService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.Itbl_PersonGroupRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
