//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface Itbl_LogService : Data.Service.IBaseService<tbl_Log>
    {
    }
    
    public partial class tbl_LogService : Data.Service.BaseService<tbl_Log>, Itbl_LogService
    {
        public tbl_LogService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.Itbl_LogRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
