//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface Itbl_PersonService : Data.Service.IBaseService<tbl_Person>
    {
    }
    
    public partial class tbl_PersonService : Data.Service.BaseService<tbl_Person>, Itbl_PersonService
    {
        public tbl_PersonService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.Itbl_PersonRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
