//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface IUser_PersonGroup_MappingService : Data.Service.IBaseService<User_PersonGroup_Mapping>
    {
    }
    
    public partial class User_PersonGroup_MappingService : Data.Service.BaseService<User_PersonGroup_Mapping>, IUser_PersonGroup_MappingService
    {
        public User_PersonGroup_MappingService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.IUser_PersonGroup_MappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
