//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Repository
{
    using System;
    using System.Collections.Generic;
    using Model.Entities;
    
    
    public partial interface ILogRepository : Data.Repository.IBaseRepository<Log>
    {
    }
    
    public partial class LogRepository : Data.Repository.BaseRepository<Log>, ILogRepository
    {
    	public LogRepository(CapstoneEntities dbContext) : base(dbContext)
        {
        }
    }
}
