//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Repository
{
    using System;
    using System.Collections.Generic;
    using Model.Entities;
    
    
    public partial interface Itbl_FaceRepository : Data.Repository.IBaseRepository<tbl_Face>
    {
    }
    
    public partial class tbl_FaceRepository : Data.Repository.BaseRepository<tbl_Face>, Itbl_FaceRepository
    {
    	public tbl_FaceRepository(CapstoneEntities dbContext) : base(dbContext)
        {
        }
    }
}
