//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Repository
{
    using System;
    using System.Collections.Generic;
    using Model.Entities;
    
    
    public partial interface Itbl_PersonGroupRepository : Data.Repository.IBaseRepository<tbl_PersonGroup>
    {
    }
    
    public partial class tbl_PersonGroupRepository : Data.Repository.BaseRepository<tbl_PersonGroup>, Itbl_PersonGroupRepository
    {
    	public tbl_PersonGroupRepository(CapstoneEntities dbContext) : base(dbContext)
        {
        }
    }
}
