//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Repository
{
    using System;
    using System.Collections.Generic;
    using Model.Entities;
    
    
    public partial interface IUser_PersonGroup_MappingRepository : Data.Repository.IBaseRepository<User_PersonGroup_Mapping>
    {
    }
    
    public partial class User_PersonGroup_MappingRepository : Data.Repository.BaseRepository<User_PersonGroup_Mapping>, IUser_PersonGroup_MappingRepository
    {
    	public User_PersonGroup_MappingRepository(CapstoneEntities dbContext) : base(dbContext)
        {
        }
    }
}
