//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.WebAPI.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IC__MigrationHistoryRepository : SkyWeb.DatVM.Data.IBaseRepository<C__MigrationHistory>
    {
    }
    
    public partial class C__MigrationHistoryRepository : SkyWeb.DatVM.Data.BaseRepository<C__MigrationHistory>, IC__MigrationHistoryRepository
    {
    	public C__MigrationHistoryRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
        {
        }
    }
}
