//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.WebAPI.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPersonGroupRepository : SkyWeb.DatVM.Data.IBaseRepository<PersonGroup>
    {
    }
    
    public partial class PersonGroupRepository : SkyWeb.DatVM.Data.BaseRepository<PersonGroup>, IPersonGroupRepository
    {
    	public PersonGroupRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
        {
        }
    }
}
