//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.WebAPI.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IUser_PersonGroup_MappingRepository : SkyWeb.DatVM.Data.IBaseRepository<User_PersonGroup_Mapping>
    {
    }
    
    public partial class User_PersonGroup_MappingRepository : SkyWeb.DatVM.Data.BaseRepository<User_PersonGroup_Mapping>, IUser_PersonGroup_MappingRepository
    {
    	public User_PersonGroup_MappingRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
        {
        }
    }
}
