//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PersonGroupViewModel
    {
    	
    			public virtual int ID { get; set; }
    			public virtual string UserID { get; set; }
    			public virtual string PersonGroupName { get; set; }
    			public virtual string Description { get; set; }
    			public virtual bool Active { get; set; }
    	}
}
