//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.WebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concept
    {
        public string ConceptId { get; set; }
        public string ConceptName { get; set; }
        public string ConceptDescription { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool Active { get; set; }
    }
}
