//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.WebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogObject
    {
        public int ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UserID { get; set; }
        public string ImageURL { get; set; }
        public bool Active { get; set; }
    }
}
