//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.WebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public string PictureId { get; set; }
        public Nullable<int> ConceptId { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public bool Active { get; set; }
    
        public virtual Concept Concept { get; set; }
    }
}
