//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.WebAPI.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ILogObjectService : SkyWeb.DatVM.Data.IBaseService<LogObject>
    {
    }
    
    public partial class LogObjectService : SkyWeb.DatVM.Data.BaseService<LogObject>, ILogObjectService
    {
        public LogObjectService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ILogObjectRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
